### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.utils._import_utils'

### ISSUE THREAD

**Issue by jellyfishovo** [SDCCA/DGL-PTM#114]
I find a similar issue happens on torch==2.3.0, and it has been solved, but in torch==2.1.0,  I try the command “import torch
torch.utils.data.datapipes.utils.common.DILL_AVAILABLE = torch.utils._import_utils.dill_available()
import torchdata” to fix this, it doesn't work.
my platform : torch==2.1.0, PyGCL==0.1.2, dgl==2.3.0+cu118, cuda==12.0
error details: 
Traceback (most recent call last):
  File "/home/sjd/Projects/New/ICASSP/train.py", line 10, in <module>
    from model import MaskedNLLLoss, LSTMModel, GRUModel, Model, MaskedMSELoss, FocalLoss
  File "/home/sjd/Projects/New/ICASSP/model.py", line 10, in <module>
    from HCL_model import HCLGNN
  File "/home/sjd/Projects/New/ICASSP/HCL_model.py", line 11, in <module>
    from GCL.models import DualBranchContrast
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/GCL/__init__.py", line 2, in <module>
    import GCL.augmentors
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/GCL/augmentors/__init__.py", line 3, in <module>
    from .rw_sampling import RWSampling
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/GCL/augmentors/rw_sampling.py", line 2, in <module>
    from GCL.augmentors.functional import random_walk_subgraph
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/GCL/augmentors/functional.py", line 6, in <module>
    from GCL.utils import normalize
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/GCL/utils.py", line 4, in <module>
    import dgl
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/dgl/distributed/dist_graph.py", line 12, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/dgl/graphbolt/__init__.py", line 39, in <module>
    from .base import *
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/dgl/graphbolt/base.py", line 21, in <module>
    from torchdata.datapipes.iter import IterDataPipe
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/torchdata/datapipes/__init__.py", line 11, in <module>
    from . import iter, map, utils
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/torchdata/datapipes/iter/__init__.py", line 79, in <module>
    from torchdata.datapipes.iter.util.cacheholder import (
  File "/home/sjd/miniconda3/envs/icassp/lib/python3.9/site-packages/torchdata/datapipes/iter/util/cacheholder.py", line 24, in <module>
    from torch.utils._import_utils import dill_available
ModuleNotFoundError: No module named 'torch.utils._import_utils'

Process finished with exit code 1

**Comment by SarahAlidoost** [comment]
@jellyfishovo The error message shows that you are using the `dgl` package rather than the `dgl_ptm` package developed in this repository. Since your issue is not related to `dgl_ptm` package, this is not the correct repository to report it. To help you, here are some links https://github.com/dmlc/dgl/issues/7380 and https://github.com/dmlc/dgl/issues/7387 to relevant issues in `dgl` repository. You might find helpful insights there on how to fix the error.
